name: "psi-gh-action"
description: "Github Action to generate web performance report using PageSpeedInsight"
author: Irfan Maulana <https://github.com/mazipan>

branding:
  icon: 'zap'
  color: 'green'

inputs:
  api_key:
    description: "PageSpeedInsight API key"
    required: true
  token:
    description: "Github token"
  branch:
    description: "Target branch to save report file"
    default: master
  push_back:
    description: "Push back the report file to the repository"
    default: false
  urls:
    description: "List of URL(s) to be analyzed"
    required: true
  devices:
    description: "Device(s) used for test"
    default: mobile
  runs:
    description: "Number of runs to do per URL"
    default: 1

runs:
  using: "node12"
  main: "dist/index.js"
