name: "static-web-perf-action"
description: "Github Action to generate web performance report in static JavaScript and JSON file using Lighthouse"

inputs:
  urls:
    description: "List of URL(s) to analyze"
    required: true
  devices:
    description: "Device(s) used for test"
    required: true
    default: mobile
  runs:
    description: "Number of runs to do per URL"
    default: 3

runs:
  using: "node12"
  main: "dist/index.js"
