on: [push]

jobs:
  psi_web_perf_action:
    runs-on: ubuntu-latest
    name: Example job
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      - name: Running PSI
        uses: ./ # Uses an action in the root directory
        id: psi_job
        with:
          api_key: ${{ secrets.PSI_API_KEY }}
          urls: |
            https://mazipan.space/
            https://mazipan.space/about/
          devices: |
            mobile
            desktop
          runs: 1
